version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: ekstraklasa_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ekstraklasa
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ekstraklasa_app
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgres://user:password@db:5432/ekstraklasa
    depends_on:
      - db
